/* Consider the following assembly code:
 *
 * long loop(long x, int n);
 *
 *
 * loop:
 *   movl %esi, %ecx  	; ecx = n
 *   movl $1, %edx 	; edx = mask = 1
 *   movl $0, %eax 	; eax = result = 0
 *   jmp .L2
 * .L3:
 *   movq %rdi, %r8	; r8 = x
 *   andq %rdx, %r8 	; r8 &= mask
 *   orq %r8, %rax	; result |= r8
 *   salq %cl, %rdx	; mask <<= n
 * .L2:
 *   testq %rdx, %rdx	; test if rdx == 0
 *   jne .L3 		; if rdx != 0, go to .L3
 *   rap; ret		; return result
 *
 *
 * The preceding code was generated by compiling C code that had the following
 * overall form:
 *
 * long loop(long x, long n) {
 * 	long result = 0;
 * 	long mask;
 * 	for (mask = 1; mask != 0; mask = mask << n) {
 * 		result |= (x & mask);
 * 	}
 * 	return result;
 * }
 *
 *
 * A/ Which registers hold program values x, n, result, and mask?
 *
 * x is held in rdi and r8
 * n is held in ecx and rsi
 * result is held in rax
 * mask is held in rdx
 * 
 *
 * B/ What are the initial values of result and mask?
 * 
 * result is initially 0. mask is initially 1.
 *
 * C/ What is the test condition for mask?
 *
 * mask != 0
 *
 * D/ How does mask get updated?
 *
 * mask <<= n
 *
 * E/ How does result get updated?
 * 
 * result |= (x & mask)
 *
 * F/ Fill in all the missing parts of the C code.
 * 
 * See C code above.
 */

int main() {
    
   
    return 0;
}
